### PR TITLE
[release-4.11] OCPBUGS-668: Fix DNS endpoint hack to prefer local instead of forcing it

### PR DESCRIPTION
**Pull request by martinkennelly**
Signed-off-by: Martin Kennelly <mkennell@redhat.com>

### CODE REVIEW

**Comment by danwinship** [comment]
yeah, looks good. If you push a PR to openshift/kubernetes I can merge it

**Comment by martinkennelly** [comment]
> yeah, looks good. If you push a PR to openshift/kubernetes I can merge it

https://github.com/openshift/kubernetes/pull/1385

Ill verify the fix and create steps for QE before removing WIP from here.

**Comment by martinkennelly** [comment]
@danwinship Confirmed this fixes the issue.

**Comment by martinkennelly** [comment]
/retest

Looks like registry pull issue.
"gather did not start for pod must-gather-gklbz: unable to pull image: ImagePullBackOff: Back-off pulling image "registry.build01.ci.openshift.org/ci-op-"

**Comment by martinkennelly** [comment]
/retest
`e2e-aws-upgrade` CI is failing because of disruption test:

```read: connection reset by peer```

This is unrelated to this PR.

**Comment by martinkennelly** [comment]
Found out the CI failure on Friday for the CI image pull was due to akamai failure.

**Comment by melvinjoseph86** [comment]
as per the comments added in OCPBUGS-668, i am marking this as verified via pre-merge workflow.
/label qe-approved

**Pull request merged**
