### PR TITLE
[release-4.8] OCPBUGS-2205: Fix DNS endpoint hack to prefer local instead of forcing it

### PR DESCRIPTION
**Pull request by martinkennelly**
Signed-off-by: Martin Kennelly <mkennell@redhat.com>

### CODE REVIEW

**Comment by melvinjoseph86** [comment]
as per the comments added in OCPBUGS-2205, i am marking this as verified via pre-merge workflow.

**Comment by martinkennelly** [comment]
@danwinship Can you take a look and add the required labels?

**Pull request merged**
