### PR TITLE
SDN-3900: rebase to 1.27.1

### PR DESCRIPTION
**Pull request by danwinship**

### CODE REVIEW

**Review by martinkennelly — APPROVED** [review]

**Comment by martinkennelly** [comment]
Tides unresponsive - maybe close and reopen?

**Comment by neisw** [comment]
/payload 4.14 nightly blocking
/payload 4.14 ci blocking

Running blocking jobs while we wait for the next merge batch window

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-upgrade 10
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade 10
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-serial

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-upgrade 10

**Pull request merged**
