### PR TITLE
WIP: Revert https://github.com/openshift/sdn/pull/440

### PR DESCRIPTION
**Pull request by DennisPeriquet**
revert https://github.com/openshift/sdn/pull/440

we think this may have caused payload rejects ; but will run tests to gather more data.

edit: realized this is against master and not release-4.11 but the testing will still be same.

### CODE REVIEW

**Comment by DennisPeriquet** [comment]
payloads never ran, see https://github.com/openshift/sdn/pull/443 with corrected branch

**Comment by stbenjam** [comment]
/reopen

GCP upgrades passed on #443, so this looks like the problem.  We'll need to revert in master, too.

**Pull request closed without merging**
