### PR TITLE
OCPBUGS-18325: Vendor o/k to consume update to prefer local TCP eps for DNS

### PR DESCRIPTION
**Pull request by martinkennelly**
/hold
/cc

### CODE REVIEW

**Comment by danwinship** [comment]
ok, o/k branch is merged

**Comment by martinkennelly** [comment]
/retitle OCPBUGS-18325: Vendor o/k to consume update to prefer local TCP eps for DNS

**Comment by martinkennelly** [comment]
@danwinship Can you reapply the labels? Tide was acting funky.

**Pull request merged**
