### PR TITLE
Bug 2002288: [4.9] proxy: don't re-check every userspace proxy rule on every change 

### PR DESCRIPTION
**Pull request by danwinship**
manual cherry-pick of #342 since it also needs a kube revendor (which I already pushed since it's identical to the already-approved 4.10 version except for the branch name)

/assign @alexanderConstantinescu

### CODE REVIEW

**Review by alexanderConstantinescu — APPROVED** [review]
/lgtm

**Comment by sdodson** [comment]
@knobunc should just need you to apply `staff-eng-approved` label now.

**Pull request merged**
