### PR TITLE
iptables: partial #13 revert, skip masq in chain

### PR DESCRIPTION
**Pull request by squeed**
PR #13 changed the source rule for OPENSHIFT-MASQUERADE. However, rolling out source-rule changes on a running system isn't clean. Easier to leave the source-rule unchanged, and just add a rule first in the chain that gets us where we want to be.
    
So, -j RETURN for traffic that's already marked for MASQ.

### CODE REVIEW

**Comment by squeed** [comment]
@danwinship PTAL.

**Comment by danwinship** [comment]
> bz1726045 / PR #8

you mean #13 

But the whole reason why created our own separate chains in the first place was so that we didn't have to do complicated cleanup (https://github.com/openshift/origin/pull/13465). We should revert that part of #13 and do this differently. Eg, if OPENSHIFT-MASQUERADE started with a "if marked then -j RETURN" rule, that would have the same effect, while leaving the toplevel rule unchanged from 4.1.

**Comment by squeed** [comment]
> if OPENSHIFT-MASQUERADE started with a "if marked then -j RETURN" rule

You're right, that's a much cleverer solution.

**Comment by squeed** [comment]
OK, updated (and fixed the commit message / title)

**Pull request merged**
