### PR TITLE
Bug 1782312: [backport] host-local plugin should be built and executed within container

### PR DESCRIPTION
**Pull request by dougbtv**
Backport of #82

### CODE REVIEW

**Comment by dougbtv** [comment]
/retest

aws ec2 instance didn't come (or looks like)

**Comment by nee1esh** [comment]
Doug, can you please update the title of this PR to point to bug
https://bugzilla.redhat.com/show_bug.cgi?id=1782312

**Comment by dougbtv** [comment]
/retitle Bug 1782312: [backport] host-local plugin should be built and executed within container

**Comment by dougbtv** [comment]
@nee1esh I got it retitled with the new BZ number. LMK if it needs anything else (currently it's complaining that it's an invalid bug)

**Comment by squeed** [comment]
/approve
/lgtm
once #82 merges, this will be valid-bug and can go in.

**Pull request merged**
