### PR TITLE
OCPBUGS-28580: Move sdn to RHEL9 base image (attempt #2)

### PR DESCRIPTION
**Pull request by jcaamano**
Install openshift clients from RPMs.

### CODE REVIEW

**Comment by jcaamano** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn-upgrade

**Comment by jcaamano** [comment]
This seems to be a flake and not related to the original GLIBC problem. Triggering again.

/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn-upgrade

**Comment by jcaamano** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn-upgrade

**Comment by jcaamano** [comment]
@danwinship @dgoodwin PTAL

**Comment by dgoodwin** [comment]
Problem looks gone. Thanks.

**Pull request merged**
