### PR TITLE
[WIP]: I want some debugging tools

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
Debugging tools...

### CODE REVIEW

**Comment by danwinship** [comment]
The sdn image gets deployed to every node; we don't want to make it bigger with stuff that isn't needed for ordinary use. You can deploy your own debugging pods to nodes. (eg, just a privileged hostNetwork `image: fedora:31` pod and then `dnf install` whatever you need).

Maybe we should create a standard network debugging pod definition in CNO or something

**Comment by alexanderConstantinescu** [comment]
> The sdn image gets deployed to every node; we don't want to make it bigger with stuff that isn't needed for ordinary use. You can deploy your own debugging pods to nodes. (eg, just a privileged hostNetwork `image: fedora:31` pod and then `dnf install` whatever you need).
> 
> Maybe we should create a standard network debugging pod definition in CNO or something

I never planned on merging this. I just needed to build an image with these tools inside as it's impossible to install packages in existing containers outside our build system due to:

```
$ yum install PACKAGE_OF_YOUR_CHOICE -y
...
a bunch of logs
...
failure: repodata/repomd.xml from rhel-fast-datapath-beta: [Errno 256] No more mirrors to try.
http://base-4-3.ocp.svc/rhel-fast-datapath-beta/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: base-4-3.ocp.svc; Unknown error"
```

**Comment by alexanderConstantinescu** [comment]
> Maybe we should create a standard network debugging pod definition in CNO or something

I like that idea however. Would we have any possibilities to deploy that pod in an easy way? I.e configuring or creating a CRD which could do something like (just thinking out loud....):

`oc network-debug node/X`

And would launch a daemonset on all nodes with those tools installed? Anything like that existing?

**Comment by alexanderConstantinescu** [comment]
> we could just have a DaemonSet yaml file in `cluster-network-operator/hack/` or something...

Well, that's....much easier. I'll try to cook something like that up

**Pull request closed without merging**
