### PR TITLE
Revert "Revert "SDN-3635: OSDN kube 1.26.0 rebase""

### PR DESCRIPTION
**Pull request by msherif1234**
Reverts openshift/sdn#508

### CODE REVIEW

**Comment by danwinship** [comment]
/hold
don't just revert the revert. Push it as multiple commits again.

It might also be helpful to push the "drop all remaining references to userspace proxy" part as a separate PR before the rebase, to get that merged and then have fewer things to debug in this one?

**Comment by msherif1234** [comment]
> /hold don't just revert the revert. Push it as multiple commits again.
> 
> It might also be helpful to push the "drop all remaining references to userspace proxy" part as a separate PR before the rebase, to get that merged and then have fewer things to debug in this one?

I want to findout about the CI breakage and so far no sign so this PR was incorrectly reverted , I will break it down as it was orginally and no need to have multiple PR we already burnt enough time here, will just wait for the current run to complete then will fix it

**Comment by danwinship** [comment]
ah, well, I filed #511; if that passes the payload test and this still fails then we could merge that to simplify this PR.

**Comment by msherif1234** [comment]
not need #510 will handle the rebase

**Pull request closed without merging**
