### PR TITLE
[Release 4.14] OCPBUGS-43484: NP-1092: backport SDN live migration

### PR DESCRIPTION
**Pull request by pliurh**
All commits were cherry-picked without conflict from master.

### CODE REVIEW

**Comment by pliurh** [comment]
@danwinship PTAL

**Comment by danwinship** [comment]
/lgtm

probably we ought to have sdn-migration CI jobs in `openshift/sdn` for 4.14, 4.15, and 4.16?

**Comment by zhaozhanqi** [comment]
This fix already be tested in https://github.com/openshift/api/pull/1994#issuecomment-2412801140

/label qe-approved

**Pull request merged**
