### PR TITLE
Bug 1852119: an iptables proxier sync fails, retry after iptablesSyncPeriod

### PR DESCRIPTION
**Pull request by juanluisvaladas**
Backport of https://github.com/kubernetes/kubernetes/pull/83387

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
I've seen in the prometheus metrics of the e2e test metric is being updated timely.

**Comment by juanluisvaladas** [comment]
After adding PR 83387 we can see a large improvement since we change from having usually a few dozen restarts of the sdn pods to just two in the e2e-aws and 3 in the e2e-aws-upgrade.

But it still had 3 restarts that must be investigated.

**Comment by danwinship** [comment]
as mentioned in https://github.com/openshift/sdn/pull/112#issuecomment-654461534, this _should_ be a no-op...

**Comment by danwinship** [comment]
/hold
@juanluisvaladas can you explain what this is doing? As mentioned in #112, the flow without this PR should be:

1. `syncProxyRules` is called
2. `proxier.changesPending` is `true`, so it skips the early exit (L704) and prepares an iptables update
3. `iptables-restore` fails, so `syncProxyRules` returns at L1454 without having unset `changesPending`
4. (SDN may become unhealthy, since iptables-restore has failed.)
5. `BoundedFrequencyRunner` calls `maybeSyncProxyRules` again after `maxInterval`, which is `syncPeriod`
6. `proxier.changesPending` is still `true`, so we do another iptables update, and hopefully succeed this time
7. Assuming we succeed, `syncProxyRules` clears `changesPending` (L1456) and updates health/metrics timestamps (L1474).
8. (SDN is now healthy again.)

AFAICT, with your patch, the sequence of events doesn't change at all; at step 3, `syncProxyRules` calls `RetryAfter(syncPeriod)`, but that just changes step 4 to "`BoundedFrequencyRunner` calls `maybeSyncProxyRules` again after `retryInterval`, which is `syncPeriod`". ie, either way, the next call to `maybeSyncProxyRules` is after `syncPeriod`. (In git master, `RetryAfter` is needed because the bfr's `maxInterval` is `time.Hour`, not `syncPeriod`.)

**Pull request closed without merging**
