### PR TITLE
Bug 1923231: rebase to sdn-4.7-kubernetes-1.20.0-rc.0

### PR DESCRIPTION
**Pull request by aojea**
Signed-off-by: Antonio Ojea <antonio.ojea.garcia@gmail.com>

### CODE REVIEW

**Comment by aojea** [comment]
/retest
failed to acquire lease

**Comment by aojea** [comment]
/assign @danwinship 
this depends on the rebase https://github.com/openshift/sdn/pull/267

**Comment by danwinship** [comment]
We should not be rebasing `release-4.7` to an `sdn-4.8-...` branch. If we need this fix in 4.7 it should be merged to the `sdn-4.7-...` branch in openshift/kubernetes and then we can rebase to that

**Comment by aojea** [comment]
backport to sdn-4.7 in openshift/kubernetes 
https://github.com/openshift/kubernetes/pull/711/files

**Pull request merged**
