### PR TITLE
[release-4.4] Bug 1874799: Add NodeInformer to EgressIP

### PR DESCRIPTION
**Pull request by danielmellado**
Backport for https://github.com/openshift/sdn/pull/171 https://github.com/openshift/sdn/pull/175
=======

* Refactor logic
* Fix calling nodeInformer in EgressIPManager.
* Add NodeInformer to EgressIP

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
/lgtm
PS: You don't need to hold, the bot won't consider the bug valid and won't let merge until the 4.5 is at least verified.

**Comment by markmc** [comment]
Fixes user-visible issue, fix has seen some good testing

**Comment by danielmellado** [comment]
Ok, so it does seem that the CI is somehow broken... /me sighs

**Comment by juanluisvaladas** [comment]
/retest
GCP has been somewhat broken all day.

**Pull request merged**
