### PR TITLE
Bug 1952079: Revendor kubernetes to sdn-4.8-kubernetes-1.21.0-rc.0

### PR DESCRIPTION
**Pull request by danwinship**
~This has no real effect other than getting people to stop being confused about why the 4.8 sdn branch refers to a 4.7 kubernetes branch. (There aren't even any differences between 1.20.0-rc.0 and 1.20.0 in the code that we vendor.)~

This updates us to 1.21.0-rc.0

(The `v0.18.6` -> `v1.21.0-rc.0` tag changes have no actual effect since we `replace` all of those modules anyway. I'm not sure why they were `v0...` rather than `v1...` before...)

/assign @squeed @juanluisvaladas

### CODE REVIEW

**Comment by aojea** [comment]
@danwinship this is panicing here
```
I0413 10:26:11.680919   24253 cmd.go:121] Reading proxy configuration from /config/kube-proxy-config.yaml
F0413 10:26:11.682492   24253 cmd.go:94] cannot set feature gate EndpointSlice to false, feature is locked to true
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc0001ac001, 0xc000472480, 0x73, 0xbf)
	k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x31da9c0, 0xc000000003, 0x0, 0x0, 0xc000582000, 0x31111e1, 0x6, 0x5e, 0x414400)
	k8s.io/klog/v2@v2.8.0/klog.go:970 +0x19b
k8s.io/klog/v2.(*loggingT).printDepth(0x31da9c0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0004e83e0, 0x1, 0x1)
	k8s.io/klog/v2@v2.8.0/klog.go:733 +0x16f
k8s.io/klog/v2.(*loggingT).print(...)
	k8s.io/klog/v2@v2.8.0/klog.go:715
k8s.io/klog/v2.Fatal(...)
	k8s.io/klog/v2@v2.8.0/klog.go:1489
github.com/openshift/sdn/pkg/openshift-sdn.(*OpenShiftSDN).Run(0xc000428070, 0xc0004ed400, 0x23aa5c0, 0xc0001ac010, 0xc000182660)
	github.com/openshift/sdn/pkg/openshift-sdn/cmd.go:94 +0x3fc
github.com/openshift/sdn/pkg/openshift-sdn.NewOpenShiftSDNCommand.func1.2(0xc000000010, 0x221e6e0)
	github.com/openshift/sdn/pkg/openshift-sdn/cmd.go:63 +0x4e
k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Run(0xc00036dd40, 0xc0006c7d38, 0x0, 0x0)
	k8s.io/kubernetes@v1.21.0-rc.0/pkg/util/interrupt/interrupt.go:103 +0xf2
github.com/openshift/sdn/pkg/openshift-sdn.NewOpenShiftSDNCommand.func1(0xc0004ed400, 0xc00032d080, 0x0, 0x8)
	github.com/openshift/sdn/pkg/openshift-sdn/cmd.go:62 +0x147
github.com/spf13/cobra.(*Command).execute(0xc0004ed400, 0xc0001b0010, 0x8, 0x8, 0xc0004ed400, 0xc0001b0010)
	github.com/spf13/cobra@v1.1.1/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004ed400, 0xd, 0x23aa5c0, 0xc0001ac010)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:800
main.main()
	github.com/openshift/sdn/cmd/openshift-sdn/openshift-sdn.go:28 +0x185
```

**Comment by danwinship** [comment]
https://github.com/openshift/cluster-network-operator/pull/1069 fixes CNO to stop passing `EndpointSlice=false`, so that has to merge first

**Comment by aojea** [comment]
/retest
one job didn't start and the other has only one failing test

**Comment by danwinship** [comment]
/retest
it's at least starting now. looks like flakes

**Comment by danwinship** [comment]
/override ci/prow/unit
fixed by #293

**Pull request merged**
