### PR TITLE
OCPBUGS-28580: Move sdn to RHEL9 base image

### PR DESCRIPTION
**Pull request by jcaamano**

### CODE REVIEW

**Comment by danwinship** [comment]
@jcaamano looks like you can't NO-JIRA a release-4.15 PR. ("Needs cherry-pick-approved, jira/valid-bug")

**Comment by jcaamano** [comment]
/retitle OCPBUGS-28580: Move sdn to RHEL9 base image

**Comment by jcaamano** [comment]
> @jcaamano looks like you can't NO-JIRA a release-4.15 PR. ("Needs cherry-pick-approved, jira/valid-bug")

worth a try :/ 
let's juggle with the bureaucracy

**Pull request merged**
