### PR TITLE
[release-4.9] OCPBUGS-2204: Fix DNS endpoint hack to prefer local instead of forcing it

### PR DESCRIPTION
**Pull request by martinkennelly**
Signed-off-by: Martin Kennelly <mkennell@redhat.com>

### CODE REVIEW

**Comment by martinkennelly** [comment]
@melvinjoseph86 Ready to go.

**Comment by melvinjoseph86** [comment]
@martinkennelly The PR is still not approved nor given  backport-risk-assessed label.

**Comment by martinkennelly** [comment]
> @martinkennelly The PR is still not approved nor given backport-risk-assessed label.

d'oh. Ill get this.

**Comment by martinkennelly** [comment]
@danwinship can you apply the two labels please?

**Pull request merged**
