### PR TITLE
[release-4.10] Bug 2064807: Rebase SDN k8 1.23.4

### PR DESCRIPTION
**Pull request by martinkennelly**
Cherry-picks from https://github.com/openshift/sdn/pull/399

Cherry-pick of [Revendor o/kubernetes and update to sdn-4.10-.. branch](https://github.com/openshift/sdn/commit/581276c7414f709762d5f1b047a831bca9d84e0d)  needed corrective action to go.mod and confirm its ok to discard changes in a non-existent file (exists on branch main: pkg/network/proxy/unidler/proxier.go ).

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm
we should let this run through tests a few times before trying to merge it

**Comment by martinkennelly** [comment]
Network stress tests
[Run #1](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1503733225522991104)

**Comment by martinkennelly** [comment]
**Network stress tests**
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1504449072667299840
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1504449041470066688
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1504449068632379392

**E2E-all**
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1504448980396806144
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1504448963879636992

No issues related to this PR.

**Comment by martinkennelly** [comment]
@danwinship Can you review and add `backport-risk-assessed` label?

**Comment by martinkennelly** [comment]
I think we are good to go here for another review.

**Comment by danwinship** [comment]
/lgtm
/label backport-risk-assessed
(Although there's a lot of new code here, most of it doesn't actually get used in openshift-sdn, and it's all been in use for a while upstream.)

**Comment by danwinship** [comment]
/hold
re aos-devel mail, this can miss next week's 4.10.z. un-/hold after Wednesday

**Pull request merged**
