### PR TITLE
Bug 1853193: [release-4.5] Backport OVS-retries

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
4.5 backport of https://github.com/openshift/sdn/pull/153 and https://github.com/openshift/sdn/pull/159

/assign @juanluisvaladas @rcarrillocruz

### CODE REVIEW

**Comment by sdodson** [comment]
@rcarrillocruz @dcbw Needs approval still, PTAL

**Comment by alexanderConstantinescu** [comment]
/hold 

I would like to get https://github.com/openshift/sdn/pull/159 in, and back-port everything together.

**Pull request merged**
