### PR TITLE
[release-4.7] Bug 2001531: improve SDN's OVS healthcheck and logging

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
4.7 back-port of #341 

/assign @danwinship

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
/retitle [release-4.7] Bug 2001531: improve SDN's OVS healthcheck and logging

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.00

adding cherry-pick approved

**Pull request merged**
