### PR TITLE
Bug 1879607: bump-k8s-to-1.19.2

### PR DESCRIPTION
**Pull request by tssurya**
This PR rebases sdn on k8sv1.19.2.
Also includes the upstream PR https://github.com/openshift/kubernetes/pull/442/commits/6e071b22148cb267190af53d9bd2520fad282602

Part of [SDN-1346](https://issues.redhat.com/browse/SDN-1346)

### CODE REVIEW

**Comment by tssurya** [comment]
wtf! locally I don't see any of the errors seen on the ci/prow/verify-deps job.

> < # sigs.k8s.io/yaml => sigs.k8s.io/yaml v1.2.0
ERROR: Content of 'vendor/' directory doesn't match 'go.mod' configuration and the overrides in 'deps.diff'!
Did you run `go mod vendor`?
If this is an intentional change (a carry patch) please update the 'deps.diff' using 'make update-deps-overrides'.
make: **** [verify-deps] Error 1

make has no right to swear I should be the one swearing -_- . Will take a look at this tomorrow,

**Comment by tssurya** [comment]
> wtf! locally I don't see any of the errors seen on the ci/prow/verify-deps job.
> 
> > < # sigs.k8s.io/yaml => sigs.k8s.io/yaml v1.2.0
> > ERROR: Content of 'vendor/' directory doesn't match 'go.mod' configuration and the overrides in 'deps.diff'!
> > Did you run `go mod vendor`?
> > If this is an intentional change (a carry patch) please update the 'deps.diff' using 'make update-deps-overrides'.
> > make: **** [verify-deps] Error 1
> 
> make has no right to swear I should be the one swearing -_- . Will take a look at this tomorrow,

ok this was happening because the ci-job was using golang 1.13 and I had 1.15.

**Comment by tssurya** [comment]
gosh did I mess up metrics point healthcheck somewhere? Cluster in trouble May day:   Warning  Unhealthy  116s (x18 over 3m21s)  kubelet, ci-ln-p3sg3qt-f76d1-mtk45-master-2  Readiness probe failed:

looking into this.

**Comment by tssurya** [comment]
> gosh did I mess up metrics point healthcheck somewhere? Cluster in trouble May day: Warning Unhealthy 116s (x18 over 3m21s) kubelet, ci-ln-p3sg3qt-f76d1-mtk45-master-2 Readiness probe failed:
> 
> looking into this.

had to update this patch to accommodate this change: https://github.com/kubernetes/kubernetes/commit/8747ba9370e950fc626c19e87ab4f7c6128bc563

**Comment by tssurya** [comment]
ok so the CI failures seem unrelated:
/cancel hold

**Comment by tssurya** [comment]
/hold

It seems like something is again wrong specific to this patch:

level=info msg=Cluster operator network Progressing is True with Deploying: DaemonSet "openshift-multus/network-metrics-daemon" is not available (awaiting 3 nodes)
level=info msg=DaemonSet "openshift-multus/multus-admission-controller" is not available (awaiting 3 nodes)

investigating....

**Comment by danwinship** [comment]
obsoleted by #227 which updates to 1.20
/close

**Pull request closed without merging**
