### PR TITLE
Bug 2060956: Separate the allPodsSelected into egress and ingress

### PR DESCRIPTION
**Pull request by wking**
Blind, mechanical backport of #404, so 4.10 CI presubmits can get going in parallel.

### CODE REVIEW

**Comment by mffiedler** [comment]
/label qe-approved

Verified on cluster-bot cluster built from this PR using the reproducer in https://bugzilla.redhat.com/show_bug.cgi?id=2060553#c13.   Service domain resolvable with the patch.

**Comment by knobunc** [comment]
/override ci/prow/e2e-aws
ci/prow/e2e-aws-upgrade

**Pull request merged**
