### PR TITLE
Bug 1853197: [release-4.4] Backport OVS-retries

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
4.4 backport of #153 and #159 

/assign @dcbw @JacobTanenbaum

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
/hold
Failure is legit in the verify test. I'll slide the fix in the next PR

**Comment by alexanderConstantinescu** [comment]
> /hold
> Failure is legit in the verify test. I'll slide the fix in the next PR

Which verify test?

```
ci/prow/verify — Job succeeded.
```

**Comment by juanluisvaladas** [comment]
/hold cancel
> Which verify test?

Sorry this was intended for a different PR. I must have commented in the wrong tab. This PR is fine :sweat:

**Comment by alexanderConstantinescu** [comment]
@dcbw / @JacobTanenbaum could you please lgmt and approve?

**Comment by dcbw** [comment]
/retest
looks like image pull failures

**Pull request merged**
