### PR TITLE
Bug 2002290: [4.8] proxy: don't re-check every userspace proxy rule on every change

### PR DESCRIPTION
**Pull request by danwinship**
backport of #342

/hold
because it depends on https://github.com/openshift/kubernetes/pull/952

### CODE REVIEW

**Comment by hardys** [comment]
[patch-manager] Approving for cherry-pick with a score of 2.00

**Comment by abhat** [comment]
@zhaozhanqi we need to get this PR verified so the 4.7 bug can move forward.

**Pull request merged**
