### PR TITLE
[WIP] stab in the dark logging to get to the bottom of endpoint issues

### PR DESCRIPTION
**Pull request by squeed**
An attempt to get to the bottom of https://bugzilla.redhat.com/show_bug.cgi?id=1765280

### CODE REVIEW

**Comment by squeed** [comment]
Need https://github.com/openshift/release/pull/5918 to merge so we can e2e-gcp

**Comment by alexanderConstantinescu** [comment]
Hey, @squeed could you also log the value of the variable `hasEndpoints` that originates from 

```
hasEndpoints := len(proxier.endpointsMap[svcName]) > 0
```

I can't rap my head around what the hell is going with this thing, during and between all, syncs.

**Comment by squeed** [comment]
Darn, this change with EVEN MORE LOGGING seems to be running correctly!

**Comment by squeed** [comment]
of course, with all the extra logging (and no code changes), the tests pass. Hmmm.

/test e2e-gcp

**Comment by squeed** [comment]
Yet another test run where everything comes up correctly.

**Comment by squeed** [comment]
green again!

/test e2e-gcp

**Comment by pecameron** [comment]
You have an interesting race here. The logging is slowing down or synchronizing the problem enough to lose the race. Maybe turn off all extra logging, just errors and maybe it will mostly fail. Aside from taking extra time, logging can serialize operations enough to get past races.

**Comment by squeed** [comment]
@pecameron yeah, I did consider that. Most of the delay in logging is in serializing the structs, so the most recent set of pushes drops all of that and adds just a few small logs. But yeah, ultimately, logging is a serialization point. 

The thing is, the race I'm considering is in the unidling proxy, which is already behind a lock (`usingUserspaceLock`) - so we're already serializing endpoint + service changes.

**Comment by danwinship** [comment]
> The thing is, the race I'm considering is in the unidling proxy, which is already behind a lock (`usingUserspaceLock`) - so we're already serializing endpoint + service changes.

Maybe the wrong thing happens when events `A` and `B` are delivered separately but the right thing happens when they get coalesced into event `B'` by the informer?

**Comment by squeed** [comment]
We have two handlers attached to the informer - the proxy, and a separate debugger. For whatever reason, the proxy handler is not seeing the only transition we're interested in (No LB IP - > LB IP). But the debug handelr (which runs *after* the proxy hander) does.

It happens to be the last transition, so all subsequent updates (which **are** seen) are short-circuited since (A = A'). 

One thing we could do is compare A' against the known state, not against A. But we should never be missing these things.

**Comment by squeed** [comment]
Just checked the CI cluster, this run will pass too. So annoying.

**Comment by pecameron** [comment]
@squeed Clearly something is different with the logging on. Working with that may back you into the problem.

**Pull request closed without merging**
